[package]
name = "main"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
anyhow = "1.0.69"
lexopt = "0.3.0"
memchr = "2.6.3"

[dependencies.shared]
path = "../../shared"

[profile.release]
debug = true
codegen-units = 1
lto = "thin"
