[package]
name = "main"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
anyhow = "1.0.69"
daachorse = "=1.0.0"
lexopt = "0.3.0"

[dependencies.shared]
path = "../../shared"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
